apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: practice
  annotations:
    github.com/project-slug: Krupakar-debuide/practice
spec:
  type: local-test
  lifecycle: Live
  owner: Krupakar
  system: Organisation
